server:
    port: 8001

spring:
    profiles:
        active: dev

    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: sa123456
    #    platform: postgres

    initialization-mode: always
    initialization: true
    continue-on-error: true
    jpa:
        hibernate:
            naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#                  ddl-auto: create
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: false
                enable_lazy_load_no_trans: true
